
spring:
  datasource:
    url: jdbc:h2:mem:members;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  data:
    rest:
      basePath: /json
