

spring:
  thymeleaf: #disable cache so we don't have to restart
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
    resources:
      static-locations: file:./src/main/resources/static/
      cache-period: 0

  datasource:
    url: jdbc:h2:mem:members;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    connectionProperties: useUnicode=true;characterEncoding=utf-8
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  data:
    rest:
      basePath: /json
server:
  port: 9090

security:
  jwt:
    secret: baus-admin-@Ckd
    expirationSecond: 18000 # 5 hours

logging.level.org.bausit.admin: DEBUG
